version: '3.8'

services:
  # frontend (React.js propulse par Node)
  web:
    build: ./site
    container_name: serveur-verif_compil
    env_file:
      - config/env/.env
    
    volumes:

      - ./site/:/app
      - /app/node_modules
    depends_on:
      - pythonserver
    networks:
      - verif_compil

  # backend (Python IA & Compilateur)
  pythonserver:
    build: ./serveurPython
    container_name: pythonserver-verif_compil
    env_file:
      - config/env/.env
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - '5000:5000'
    networks:
      - verif_compil

  # Routeur Nginx
  nginx-proxy:
    image: 'nginx:stable-alpine'
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    
    depends_on:
      - web
      - pythonserver
    networks:
      - verif_compil

networks:
  verif_compil:
    driver: bridge
