name: CD-Pipeline
# version pour avoir une pipeline
on:
  workflow_run:
    workflows: ["CI-VerifCompil"] 
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Deploiement serveur
    # si CI ok alors 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted 
    steps:
      - name: Verification code
        uses: actions/checkout@v4

      - name: Crée dossier config et fichier .env
        run: |
          mkdir -p config/env
          echo "${{ secrets.ENV_FILE_CONTENT }}" > config/env/.env
          chmod 600 config/env/.env

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            python:
              - 'serveurPython/**'
            site:
              - 'site/**'
            nginx:
              - 'config/nginx/**'

      - name: recompose Python
        if: steps.changes.outputs.python == 'true'
        run: | 
          docker compose up --build -d pythonserver 

      - name: recompose les services web
        if: steps.changes.outputs.site == 'true' || steps.changes.outputs.nginx == 'true'
        run: |
          docker compose up --build -d web nginx-proxy

      
