name: CD-Pipeline

on:
  workflow_run:
    workflows: ["CI-VerifCompil"] 
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    name: Deploiement serveur
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted 
    steps:
      - name: MaJ code
        uses: actions/checkout@v4

      - name: config .env
        run: |
          mkdir -p config/env
          echo "${{ secrets.ENV_FILE_CONTENT }}" > config/env/.env
          echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
          chmod 600 config/env/.env

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            python:
              - 'serveurPython/**'
            site:
              - 'site/**'
            nginx:
              - 'config/nginx/**'
            docker:
              - 'docker-compose.yml'

      - name: MaJ services
        run: |
          if [ "${{ steps.changes.outputs.python }}" == "true" ]; then
            echo "rebuild backend"
            docker compose up -d --build
          fi

          if [ "${{ steps.changes.outputs.site }}" == "true" ] || [ "${{ steps.changes.outputs.nginx }}" == "true" ]; then
            echo "rebuild web"
            docker compose up -d --build web nginx-proxy
          fi
          
          if [ "${{ steps.changes.outputs.docker }}" == "true" ]; then
            echo "remonter le compose"
            docker compose up -d
          fi

      - name: supp images inutiles
        run: docker image prune -f