name: CI-VerifCompil

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lesTestsU:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Config python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les outils de test
        run: |
          pip install flake8 pytest requests flask openai 
          sudo apt-get update && sudo apt-get install -y clang

      - name: Vérification syntaxe 
        run: |
          #si erreur synthaxe py
          flake8 serveurPython --count --select=E9,F63,F7,F82 --show-source --statistics

      # revoir les tests unitaires
      #- name: Test logique compilation (Clang)
      #  run: python3 tests/testClang.py

  dockerTest:
    needs: lesTestsU
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: .env de test
        run: |
          echo "DB_USER=admin" > .env
          echo "DB_PASSWORD=password123" >> .env
          echo "DB_NAME=verif_bdd" >> .env
          echo "API_KEY_DEEPSEEK=fake_key" >> .env

      - name: Build avec le compose ci
        run: |
         
          docker compose -f docker-compose.ci.yaml up -d --build

      - name: attente du build
        run: |
          timeout 60s bash -c 'until curl -s http://localhost:8080/api/health; do sleep 2; done' || (docker compose -f docker-compose.ci.yaml logs && exit 1)

      #- name: Exécuter les tests d'intégration
      #  run: python3 tests/testCompil.py
      #  env:
      #    TEST_SERVER_URL: http://localhost:8080

      - name: Afficher les logs en cas d'échec
        if: failure()
        run: |
          docker compose -f docker-compose.ci.yaml ps
          docker compose -f docker-compose.ci.yaml logs pythonserver
          docker compose -f docker-compose.ci.yaml logs db

      - name: Clean up
        if: always()
        run: docker compose -f docker-compose.ci.yaml down
        