name: CI-VerifCompil         

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]                  

jobs:
  verification-projet:        
    runs-on: ubuntu-latest   

    steps:                      
      - name: Recup fichier
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dependances Python
        run: |
          pip install requests flask openai 

      - name: Test de la fonction de compilation (Clang)
        run: |
          sudo apt-get install -y clang
          # Assure-toi que ce fichier existe dans /tests/
          python3 tests/testClang.py

      #- name: Vérification syntaxe Backend
      #  run: |
      #    cd serveurPython
      #    # Correction : le module est 'py_compile', pas 'compile_code'
      #    python3 -m py_compile app.py 

      - name: Préparer faux .env 
        run: |
          mkdir -p config/env
          echo "API_KEY_DEEPSEEK=fake_key_for_ci" > config/env/.env

      - name: Lancer les conteneurs pour test
        run: docker compose -f docker-compose.ci.yaml up -d

      - name: Attendre que le serveur soit prêt
        run: sleep 20 # On augmente un peu pour être sûr

      - name: tests des fonctions back
        run: python3 tests/testCompil.py
        env:
          TEST_SERVER_URL: http://localhost:8080

      - name: Afficher les logs en cas d'échec
        if: failure() # S'exécute SEULEMENT si une étape précédente a raté
        run: |
          docker compose -f docker-compose.ci.yaml ps
          docker compose -f docker-compose.ci.yaml logs pythonserver
          docker compose -f docker-compose.ci.yaml logs nginx-proxy

      - name: Arrêter les conteneurs
        run: docker compose -f docker-compose.ci.yaml down

# tester le front mais c compliqué

      - name: Resultat
        run: echo "CI terminée"
